name: SmartFarmz
description: Smart Farmz is an App for Farmers to efficiently manage their farms and Orchards.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+34

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  line_awesome_flutter: ^1.0.1
  #flutter_screenutil: ^1.0.2
  http: ^0.12.0+4
  json_serializable: ^3.2.5
  flutter_facebook_login: ^3.0.0
 
  json_table: ^1.4.0
  data_tables: ^1.0.3
  path_provider: ^1.6.9
  path: ^1.6.4
  image_picker: ^0.6.7
  shared_preferences: ^0.5.4
  provider: 4.1.2
  flutter_icons: ^1.1.0
  flutter_launcher_icons: ^0.7.5
  searchable_dropdown: ^1.1.3
  lite_rolling_switch: ^0.1.1
  share: ^0.6.5+1
  wc_flutter_share: ^0.2.2
  rating_bar: ^0.2.0
  flutter_swiper: ^1.1.6
  #photo_view: ^0.10.3
  #flutter_image_compress: ^0.7.0
  #multi_image_picker: ^4.7.14
  #flutter_absolute_path: ^1.0.6
  #android_intent: ^0.3.7+2
  #firebase_core: ^0.4.0+9
  #firebase_auth: ^0.16.1
  #firebase_auth_web: ^0.1.3+1

  
 
  
  
  flutter_localizations:
    sdk: flutter  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.16.1
  flutter_localized_locales: ^1.1.2
  cupertino_icons: ^0.1.3
  #rally_assets: ^2.0.0
  meta: ^1.1.8
  scoped_model:
  #shrine_images: ^1.1.2
  flare_flutter: ^2.0.2
  url_launcher: ^5.4.10
  collection: ^1.14.0
  package_info: ^0.4.0
  google_fonts: ^1.0.0
  flutter_staggered_grid_view: ^0.3.0
  internationalization: ^2.0.0
  
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  flutter_driver:
    sdk: flutter
  test: any
  grinder: ^0.8.0
  intl_translation:
  pedantic: ^1.9.0
  string_scanner: ^1.0.5
  

flutter_icons:
  android: true 
  ios: true
  image_path_android: "assets/img/icon/smartfarmz.png"
  image_path_ios: "assets/img/icon/smartfarmz.png"
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true



  # To add assets to your application, add an assets section, like this:
  assets:
  - lang/en.json
  - lang/te.json
 

  - assets/img/SmartFarms.png

  

  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    #- family: Raleway
    #  fonts:
    #    - asset: assets/fonts/Raleway-Regular.ttf
    #     weight: 700
    #    - asset: assets/fonts/Raleway-Bold.ttf
    #      weight: 700
    #    - asset: assets/fonts/Raleway-Black.ttf
    #      style: italic
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 700
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700

    - family: whatsApp
      fonts:
       - asset: assets/fonts/whatsApp.ttf
          
    #- family: RobotoCondensed
    #  fonts:
    #    - asset: assets/fonts/RobotoCondensed-Light.ttf
    #    - asset: assets/fonts/RobotoCondensed-Regular.ttf
    #      weight: 700

    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
